### ISSUE TITLE
Wont node

### ISSUE THREAD

**Issue by Nmatheny1726** [vkarpov15/stopwatch-server-example#1]
When i try to run the node i am receiving errors
 Error: Cannot find module 'http-errors'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Nathan\Desktop\Stopex\node_modules\loopback\node_modules\express\node_modules\send\index.js:15:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

**Comment by vkarpov15** [comment]
What version of npm are you using? If you're on `>= 3.0.0 <= 3.4.0` you're probably getting bitten by https://github.com/npm/npm/pull/10338, so upgrade to at least 3.4.1.

**Comment by Nmatheny1726** [comment]
That is what I had to do. Thanks !! Sorry I forgot to update to fixed got called into work. Great work on this program by the way!
